publish_to: none

name: live_captions_xr
description: A Flutter app for live captions and XR accessibility features.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  scidart: ^0.0.2-dev.12
  shared_preferences: ^2.5.3
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  flutter_launcher_icons: ^0.14.4
  flutter_gemma: ^0.9.0
  whisper_ggml: ^1.4.0
  
  device_info_plus: ^11.5.0
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  provider: ^6.1.2
  http: ^1.4.0
  dart_openai: ^5.1.0
  flutter_dotenv: ^5.1.0
  
  google_sign_in: ^6.2.1
  audio_streamer: ^4.2.2
  # Add your other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/models/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf

# add section for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logos/logo.png
  web:
    generate: true
    image_path: assets/logos/logo.png
    background_color: "#ffffff"
    theme_color: "#1E40AF"
  windows:
    generate: true
    image_path: assets/logos/logo.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/logos/logo.png

