
import 'package:meta/meta.dart';

/// Base class for multimodal events (sound, visual, etc.)
///
/// Provides a standardized structure for events that can be processed
/// by the multimodal AI engine, ensuring consistent handling of
/// confidence, context, and metadata.
@immutable
abstract class MultimodalEvent {
  /// Confidence score from 0.0 to 1.0
  final double confidence;

  /// Natural language description generated by AI analysis
  final String description;

  /// Additional metadata for enhanced features
  final Map<String, dynamic> metadata;

  const MultimodalEvent({
    required this.confidence,
    this.description = '',
    this.metadata = const {},
  });
}
