name = "livecaptionsxr-models"
compatibility_date = "2025-01-01"
main = "./src/index.js"

[assets]
directory = "."
binding = "ASSETS"

[[routes]]
pattern = "livecaptionsxrbucket.com/*"
zone_id = "a6b749215c45e9a1edb86425f0f592a7" 